#!/usr/bin/env bash

# This script displays the message "To infinity and beyond" indefinitely
# with a sleep of 2 seconds between each iteration.

# The `while` loop will keep running indefinitely since the condition is always true.
while true
do
  # Display the message "To infinity and beyond" to the console.
  echo "To infinity and beyond"

  # Pause the script execution for 2 seconds before the next iteration.
  sleep 2
done
