#!/usr/bin/env bash

# This script displays the messages "To infinity and beyond" and "I am invincible!!!"
# indefinitely with a sleep of 2 seconds between each iteration.

# The `while` loop will keep running indefinitely since the condition is always true.
while true
do
  # Display the message "To infinity and beyond" to the console.
  echo "To infinity and beyond"

  # Pause the script execution for 2 seconds before the next iteration.
  sleep 2

  # The `trap` command sets up an action to be taken when the script receives the SIGTERM signal.
  # When the script receives SIGTERM, it will execute the specified command, which is to display
  # the message "I am invincible!!!" to the console.
  trap 'echo "I am invincible!!!"' SIGTERM
done
