#!/usr/bin/env bash
# This script displays the message "To infinity and beyond" indefinitely
# with a sleep of 2 seconds between each iteration.
# Additionally, it displays the message "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
