#!/usr/bin/env bash

# This script kills the process named "7-highlander" using the `pkill` command
# with the SIGKILL signal (-9).

# The `pkill` command is used to find and terminate processes based on their names.
# The `-f` option is used to match the entire command line, and the `-SIGKILL` (or `-9`)
# option is used to send the SIGKILL signal to the matched process, forcefully terminating it.

# The process named "7-highlander" will be forcefully terminated with the SIGKILL signal.
pkill -f -SIGKILL 7-highlander
